#!/bin/bash
clear
fun_online() {
	ps -x | grep sshd | grep -v root | grep priv | wc -l > /var/www/html/server/online
}
while true; do
    echo 'verificando...'
	fun_online > /dev/null 2>&1
	sleep 15s
done
