#!/bin/bash
clear
slowdns () {
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "MENU SLOWDNS MANAGER V3.0" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[0;36m#===================================================#\033[m"
echo -e "\033[0;36m# .|'''.|'||                '||''|. '|.   '|'.|'''.|#\033[m"
echo -e "\033[0;36m# ||..  ' ||  ... ... ... ...||   || |'|   | ||..  '#\033[m"
echo -e "\033[0;36m#  ''|||. ||.|  '|.||  ||  | ||    ||| '|. |  ''|||.#\033[m"
echo -e "\033[0;36m#.     '||||||   || ||| |||  ||    |||   |||.     '|#\033[m"
echo -e "\033[0;36m#|'....|'.||.'|..|'  |   |  .||...|'.|.   '||'....|'#\033[m"
echo -e "\033[0;36m#---------------------------------------------------#\033[m"
echo -e "\033[0;36m#\033[m \033[0;31mSlowDNS | Desfrute e passe tempo\033[m \033[0;36m#\033[m"
echo -e "\033[0;36m#===================================================#\033[m"
    echo ""
    echo -e "\033[0;36m[01]\033[m | Instalar SlowDNS SSH"
    echo -e "\033[0;36m[02]\033[m | Instalar SlowDNS SSL"
    echo -e "\033[0;36m[03]\033[m | Instalar SlowDNS SOCKS"
    echo -e "\033[0;36m[04]\033[m | Ver informações"
    echo -e "\033[0;36m[05]\033[m | Iniciar SlowDNS"
    echo -e "\033[0;36m[06]\033[m | Reiniciar SlowDNS"
    echo -e "\033[0;36m[07]\033[m | Parar SlowDNS"
    echo -e "\033[0;36m[08]\033[m | Remover SlowDNS"
    echo -e "\033[0;36m[09]\033[m | Voltar Para Conexoes"
    echo ""
    echo -ne "\033[0;36mO que deseja fazer?:\0033[m " && read opcao
    case $opcao in
    1) Opcao1 ;;
    2) Opcao2 ;;
    3) Opcao3 ;;
    4) Opcao4 ;;
    5) Opcao5 ;;
    6) Opcao6 ;;
    7) Opcao7 ;;
    8) Opcao8 ;;
    9) Opcao9 ;;
    0) Sair ;;
    *) "Calma Barboleta" ; echo ; slowdns ;;
    esac
    }

Opcao1 () {
    clear
    bash /etc/slowdns/slowdns-ssh
clear
cd /bin/ && slowdns
}
Opcao2 () {
    clear
    bash /etc/slowdns/slowdns-ssl
clear
cd /bin/ && slowdns
}
Opcao3 () {
    clear
    bash /etc/slowdns/slowdns-socks
clear
cd /bin/ && slowdns
}
Opcao4 () {
    clear
    bash /etc/slowdns/slowdns-info
clear
cd /bin/ && slowdns
}
Opcao5 () {
    clear
    bash /etc/slowdns/startdns
sleep 5s
clear
cd /bin/ && slowdns
}
Opcao6 () {
    clear
    bash /etc/slowdns/restartdns
sleep 5s
clear
cd /bin/ && slowdns
}
Opcao7 () {
    clear
    bash /etc/slowdns/stopdns
sleep 5s
clear
cd /bin/ && slowdns
}
Opcao8 () {
     clear
    bash /etc/slowdns/stopdns
    bash /etc/slowdns/remove-slow
clear
cd /bin/ && slowdns
}
Opcao9 () {
    clear
cd /bin/ && conexao
}
Sair() {
    clear
    menu
}
clear
slowdns
